version: '3.7'

services:
  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - web
      - api
    ports:
      - ${PORT}:80
    volumes:
      - .:/var/www/web
      - ./backend:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - PORT=5000
    expose:
      - 5000
    volumes:
      - .:/var/www/web

  api:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.api
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    expose:
      - 3000
    volumes:
      - ./backend:/var/www/api

  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./var/db:/var/lib/postgresql/data
