version: '3.7'
services:
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
    restart: always
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 54322:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - POSTGRES_HOST
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - PRIVATE_KEY
    restart: unless-stopped
    ports:
      - 7000:3000
    depends_on:
      - db

volumes:
  pgdata:
